# Generated by Django 3.0.2 on 2020-01-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='plot_size',
            new_name='phone_no',
        ),
    ]
