# Generated by Django 3.0.2 on 2020-01-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20200124_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
