# Generated by Django 3.0.2 on 2020-01-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phone_no',
            new_name='plot_size',
        ),
    ]
