# Generated by Django 3.0.2 on 2020-01-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
