# Generated by Django 3.0.2 on 2020-01-24 08:45

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('description', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('bedrooms_no', models.PositiveIntegerField()),
                ('bathrooms_no', models.PositiveIntegerField()),
                ('plot_size', models.PositiveIntegerField()),
                ('cost', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
