# Generated by Django 3.0.2 on 2020-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='house_image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
